name: Deploy

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      - name: Copy files
        run: 'cp package.json build/package.json && cp package-lock.json build/package-lock.json'

      - name: Commit and push
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git switch foo
          git pull

          # If your production files are in 'dist/' or similar, move them as needed
          git add build/ -f # Replace with your build directory

          # Commit changes if any files were updated
          git diff --quiet || git commit -m "Build: Update production bundle"

          # Push to the target branch
          git push origin HEAD:build

      - name: Pull and run
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo -u qjcr bash
            cd ~/abortorium/
            git pull
            npm install
            node build
