name: Deploy

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      - name: Copy package data
        run: "cp package.json build/package.json && cp package-lock.json build/package-lock.json"

      - name: Checkout the target branch
        run: |
          git checkout --orphan -b dist || git checkout --orphan dist
          git rm -rf .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
  
      - name: Commit and Push
        run: |
          git add -f build/
          git mv build/package.json package.json
          git mv build/package-lock.json package-lock.json
          git add -f package.json
          git add -f package-lock.json
          git commit -m "Update build artifacts" || echo "No changes to commit"
          git push origin dist --force # Push to the target branch

      - name: Pull and run
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            whoami
            whoami
            node -v
            nvm use node
            cd /societies/qjcr/abortorium
            git config --global --add safe.directory /societies/qjcr/abortorium
            git reset --hard origin/dist
            npm ci --omit dev
            node --env-file=.env build # yay
